### ISSUE TITLE
Test cases aren't running in cloud build

### ISSUE THREAD

**Issue by abu-yusuf-dev** [GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild#5]
I followed this script to run my app in the cloud run. All the steps were running properly except test cases.

**Comment by abu-yusuf-dev** [comment]
This worked properly:

```
- name: 'python:3.7'
    id: Test
    entrypoint: 'bash'
    args:
      - '-c'
      - |
         pip3 install -r requirements.txt
         python3 test_app.py .
```
